tap "1password/tap"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "hudochenkov/sshpass"
tap "kreuzwerker/taps"
tap "mutagen-io/mutagen"
brew "openssl@3"
brew "python@3.11"
brew "ansible"
brew "black"
brew "yamllint"
brew "ansible-lint"
brew "coreutils"
brew "docker"
brew "fish"
brew "gh"
brew "graphviz"
brew "openssl@1.1"
brew "jsonschema"
brew "just"
brew "krb5"
brew "libmagic"
brew "nuclei"
brew "nvm"
brew "postgresql@12", restart_service: true
brew "virtualenv", link: false
brew "pre-commit"
brew "pyenv"
brew "python@3.10"
brew "tcl-tk"
brew "python@3.8"
brew "redis", restart_service: true
brew "tfenv"
brew "tflint"
brew "zlib"
brew "hashicorp/tap/terraform", link: false
brew "hudochenkov/sshpass/sshpass"
brew "kreuzwerker/taps/m1-terraform-provider-helper"
brew "mutagen-io/mutagen/mutagen"
cask "1password-cli"
cask "eloston-chromium"
cask "font-hack-nerd-font"
cask "obsidian"
cask "raspberry-pi-imager"
cask "rectangle"
cask "thunderbird"
mas "Jira", id: 1475897096
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Reeder", id: 1529448980
mas "Todoist", id: 585829637
mas "Xcode", id: 497799835
vscode "CircleCI.circleci"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "GitHub.copilot"
vscode "GitHub.copilot-chat"
vscode "hashicorp.terraform"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "PKief.material-icon-theme"
vscode "redhat.ansible"
vscode "redhat.vscode-yaml"
vscode "timonwong.shellcheck"
