tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "wtfutil/wtfutil"
brew "allure"
brew "ansible"
brew "node"
brew "appium"
brew "automake"
brew "bash-completion"
brew "carthage"
brew "coreutils"
brew "cask"
brew "circleci"
brew "dos2unix"
brew "ruby"
brew "fastlane", link: false
brew "fzf"
brew "gh"
brew "git"
brew "glib"
brew "openjdk@11"
brew "gradle"
brew "grep"
brew "imagemagick"
brew "libimobiledevice"
brew "ios-webkit-debug-proxy"
brew "jq"
brew "kubernetes-cli", link: false
brew "libksba"
brew "mas"
brew "minikube"
brew "moreutils"
brew "rbenv"
brew "rename"
brew "shellcheck"
brew "tree"
brew "watchman"
brew "wtfutil"
brew "yarn"
brew "youtube-dl"
brew "zlib"
cask "1password"
cask "adoptopenjdk"
cask "android-sdk"
cask "balenaetcher"
cask "discord"
cask "fantastical"
cask "figma"
cask "firefox"
cask "firefox-developer-edition"
cask "font-jetbrains-mono"
cask "google-chrome"
cask "grammarly"
cask "gswitch"
cask "hey"
cask "ilya-birman-typography-layout"
cask "intellij-idea-ce"
cask "lastpass"
cask "monitorcontrol"
cask "ngrok"
cask "notion"
cask "openvpn-connect"
cask "proxyman"
cask "signal"
cask "skype"
cask "spectacle"
cask "spotify"
cask "steam"
cask "tor-browser"
cask "tunnelbear"
cask "visual-studio-code"
cask "webstorm"
cask "yandex-cloud-cli"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Jira", id: 1475897096
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Reeder", id: 1529448980
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Telegram Lite", id: 946399090
mas "Todoist", id: 585829637
mas "Xcode", id: 497799835
